seo:
  site_name: Essentie Bazel
  title: S&SI Body- and Beautysalon Bazel
  description:  Welkom bij S&SI Bazel, uw rustpunt tussen Antwerpen en het Waasland. Wij bieden brede selectie aan ontspannende en medisch verantwoorde verzorgingen. Geniet van onze behandelingen en ontvang deskundig advies over schoonheidsproducten die bij u passen. Of het nu voor een speciale gelegenheid is of gewoon om te ontspannen, stel bij ons een arrangement samen op maat van uw wensen en budget.
  keywords: essentie bazel, schoonheidsinstituut, schoonheidssalon, schoonheidsspecialiste, medische pedicure, gelaatsverzorging, lichaamsverzorging, ontharing, permanente make-up, nagelstudio, nagelverzorging, wimperextensions, wimperlifting, gellak, gelnagels, manicure, pedicure, massage, huidanalyse, huidverbetering, huidverjonging, huidverzorging, huidverzorgingsproducten, make-up, make-up advies, make-up workshop, make-up artist, make-up producten, make-up studio, make-up tips
  social_image: /images/essentie.nancy.jpg
  author: Nancy De Jonghe
  favicon_image: /icons/favicon.svg
social:
  instagram_username: https://www.instagram.com/essentieburcht/
  facebook_url: https://www.facebook.com/profile.php?id=100063813212756
  twitter_username:
design:
  dark-text_color:
  medium-text_color:
  light-text_color:
  featured-text_color:
  dark_color:
  medium_color:
  light_color:
  v-light_color:
  featured_color:
  accent_color:
