seo:
  site_name: OSSM
  title: 
  description: 
  keywords: 
  social_image: 
  author: Lindsay Nevejans
  favicon_image: /icons/favicon.svg
social:
  instagram_username: 
  facebook_url: 
  twitter_username:
design:
  dark-text_color:
  medium-text_color:
  light-text_color:
  featured-text_color:
  dark_color:
  medium_color:
  light_color:
  v-light_color:
  featured_color:
  accent_color:
